### ISSUE TITLE
error in latest deploy action

### ISSUE THREAD

**Issue by kachick** [mobu-of-the-world/mobu#1083]
https://github.com/mobu-of-the-world/mobu/actions/runs/6077686693/job/16487768733

```
> vite build

failed to load config from /home/runner/work/mobu/mobu/vite.config.ts
error during build:
TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/home/runner/work/mobu/mobu/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:[11](https://github.com/mobu-of-the-world/mobu/actions/runs/6077686693/job/16487768733#step:5:12)15:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/runner/work/mobu/mobu/node_modules/@babel/core/lib/config/helpers/config-api.js:16:9)
    at Module._compile (node:internal/modules/cjs/loader:[12](https://github.com/mobu-of-the-world/mobu/actions/runs/6077686693/job/16487768733#step:5:13)41:[14](https://github.com/mobu-of-the-world/mobu/actions/runs/6077686693/job/16487768733#step:5:15))
Error: Process completed with exit code 1.
```

**Comment by pankona** [comment]
oyaoya

**Comment by nicolo-ribaudo** [comment]
Caused by https://github.com/nodejs/node/pull/47999
